const UPDATE_USER = 'auth/UPDATE_USER';
const UPDATE_JWT = 'auth/UPDATE_JWT';
const UPDATE_IS_LOADING = 'auth/UPDATE_IS_LOADING';
const UPDATE_IS_AUTHENTICATED = 'auth/UPDATE_IS_AUTHENTICATED';
const UPDATE_USER_DATA = 'auth/UPDATE_USER_DATA';
const UPDATE_IS_USER_UPDATING = 'auth/UPDATE_IS_USER_UPDATING';
const UPDATE_IS_SET_UP = 'auth/UPDATE_IS_SET_UP';

export default {
  UPDATE_USER,
  UPDATE_JWT,
  UPDATE_IS_LOADING,
  UPDATE_IS_AUTHENTICATED,
  UPDATE_USER_DATA,
  UPDATE_IS_USER_UPDATING,
  UPDATE_IS_SET_UP
};
