const UPDATE_LOADED = 'appInfo/UPDATE_LOADED';
const UPDATE_CONNECTED = 'appInfo/UPDATE_CONNECTED';
const UPDATE_SERVERVERSION = 'appInfo/UPDATE_SERVERVERSION';
const UPDATE_USER_STATUS = 'appInfo/UPDATE_USER_STATUS';

export default {
  UPDATE_LOADED,
  UPDATE_CONNECTED,
  UPDATE_SERVERVERSION,
  UPDATE_USER_STATUS
};
