const UPDATE_LOADED = 'appInfo/UPDATE_LOADED';
const UPDATE_CONNECTED = 'appInfo/UPDATE_CONNECTED';
const UPDATE_SERVERVERSION = 'appInfo/UPDATE_SERVERVERSION';
const UPDATE_USER_STATUS = 'appInfo/UPDATE_USER_STATUS';
const UPDATE_THEME = 'appInfo/UPDATE_THEME';
const UPDATE_BANNERASHEADER = 'appInfo/UPDATE_BANNERASHEADER';
const UPDATE_COMICSANS = 'appInfo/UPDATE_COMICSANS';
const ADD_NOTIFICATION = 'appInfo/ADD_NOTIFICATION'

export default {
  UPDATE_LOADED,
  UPDATE_CONNECTED,
  UPDATE_SERVERVERSION,
  UPDATE_USER_STATUS,
  UPDATE_THEME,
  UPDATE_BANNERASHEADER,
  UPDATE_COMICSANS,
  ADD_NOTIFICATION
};
