const UPDATE_LOADED = 'status/UPDATE_LOADED';
const UPDATE_STATUS = 'status/UPDATE_STATUS';
const UPDATE_EVENTS = 'status/UPDATE_EVENTS';
const UPDATE_BOTLANGUAGE = 'status/UPDATE_BOTLANGUAGE';
const UPDATE_STARTING = 'status/UPDATE_STARTING';
const UPDATE_STOPPING = 'status/UPDATE_STOPPING';

export default {
  UPDATE_LOADED,
  UPDATE_STATUS,
  UPDATE_EVENTS,
  UPDATE_BOTLANGUAGE,
  UPDATE_STARTING,
  UPDATE_STOPPING
};
