const UPDATE_SPOTIFYACCOUNT = 'spotify/UPDATE_SPOTIFYACCOUNT';
const UPDATE_SPOTIFYAUTHURI = 'spotify/UPDATE_SPOTIFYAUTHURI';
const UPDATE_SPOTIFYDISCONNECT = 'spotify/UPDATE_SPOTIFYDISCONNECT';
const UPDATE_DISABLED = 'spotify/UPDATE_DISABLED';
const UPDATE_IS_LOADING = 'spotify/UPDATE_IS_LOADING';

export default {
  UPDATE_SPOTIFYACCOUNT,
  UPDATE_SPOTIFYAUTHURI,
  UPDATE_SPOTIFYDISCONNECT,
  UPDATE_DISABLED,
  UPDATE_IS_LOADING
};
