const UPDATE_THEMES = 'themes/UPDATE_THEMES';
const UPDATE_THEMERESPONSE = 'themes/UPDATE_THEMERESPONSE';
const UPDATE_ADDTHEME = 'themes/UPDATE_ADDTHEME';
const UPDATE_PAGINATION = 'themes/UPDATE_PAGINATION';
const UPDATE_LOADING = 'themes/UPDATE_LOADING';
const UPDATE_LOADED = 'themes/UPDATE_LOADED';
const UPDATE_ACTIONSUCCESS = 'themes/UPDATE_ACTIONSUCCESS';

export default {
  UPDATE_THEMES,
  UPDATE_THEMERESPONSE,
  UPDATE_ADDTHEME,
  UPDATE_PAGINATION,
  UPDATE_LOADING,
  UPDATE_LOADED,
  UPDATE_ACTIONSUCCESS
};
