const UPDATE_LOADED = 'plugins/UPDATE_LOADED';
const UPDATE_PLUGINS = 'plugins/UPDATE_PLUGINS';
const UPDATE_ALLPLUGINS = 'plugins/UPDATE_ALLPLUGINS';
const UPDATE_PAGINATION = 'plugins/UPDATE_PAGINATION';
const SET_INSTALLED = 'plugins/SET_INSTALLED';
const UPDATE_LOADING = 'plugins/UPDATE_LOADING';
const UPDATE_QUERY = 'plugins/UPDATE_QUERY';
const UPDATE_ACTION_IN_PROGRESS = 'plugin/UPDATE_ACTION_IN_PROGRESS';
const UPDATE_ACTIONSUCCESS = 'plugins/UPDATE_ACTIONSUCCESS';

export default {
  UPDATE_LOADED,
  UPDATE_PLUGINS,
  UPDATE_ALLPLUGINS,
  UPDATE_PAGINATION,
  SET_INSTALLED,
  UPDATE_LOADING,
  UPDATE_QUERY,
  UPDATE_ACTION_IN_PROGRESS,
  UPDATE_ACTIONSUCCESS
};
