const UPDATE_LOADED = 'plugins/UPDATE_LOADED';
const UPDATE_PLUGINS = 'plugins/UPDATE_PLUGINS';
const SET_INSTALLED = 'plugins/SET_INSTALLED';
const UPDATE_LOADING = 'plugins/UPDATE_LOADING';
const UPDATE_QUERY = 'plugins/UPDATE_QUERY';

export default {
  UPDATE_LOADED,
  UPDATE_PLUGINS,
  SET_INSTALLED,
  UPDATE_LOADING,
  UPDATE_QUERY
};
