const UPDATE_LASTSTREAM = 'laststream/UPDATE_LASTSTREAM';
const UPDATE_ALLSTREAMDATA = 'laststream/UPDATE_ALLSTREAMDATA';
const UPDATE_DISABLED = 'laststream/UPDATE_DISABLED';

export default {
  UPDATE_LASTSTREAM,
  UPDATE_ALLSTREAMDATA,
  UPDATE_DISABLED
};
