const UPDATE_STREAMTRACKER = 'streamtracker/UPDATE_STREAMTRACKER';
const UPDATE_GLOBALSTREAMTRACKER = 'streamtracker/UPDATE_GLOBALSTREAMTRACKER';
const UPDATE_DISABLED = 'streamtracker/UPDATE_DISABLED';

export default {
  UPDATE_STREAMTRACKER,
  UPDATE_GLOBALSTREAMTRACKER,
  UPDATE_DISABLED
};
