const UPDATE_STREAMTRACKER = 'streamtracker/UPDATE_STREAMTRACKER';
const UPDATE_GLOBALSTREAMTRACKER = 'streamtracker/UPDATE_GLOBALSTREAMTRACKER';
const UPDATE_DISABLED = 'streamtracker/UPDATE_DISABLED';
const UPDATE_LOADED = 'streamtracker/UPDATE_LOADED';
const UPDATE_LOADING = 'streamtracker/UPDATE_LOADING';
const UPDATE_GLOBALLOADING = 'streamtracker/UPDATE_GLOBALLOADING';

export default {
  UPDATE_STREAMTRACKER,
  UPDATE_GLOBALSTREAMTRACKER,
  UPDATE_DISABLED,
  UPDATE_LOADED,
  UPDATE_LOADING,
  UPDATE_GLOBALLOADING
};
