const UPDATE_LOADED = 'support/UPDATE_LOADED';
const UPDATE_MY_TICKETS = 'support/UPDATE_MY_TICKETS';
const UPDATE_ADMIN_TICKETS = 'support/UPDATE_ADMIN_TICKETS';

export default {
  UPDATE_LOADED,
  UPDATE_MY_TICKETS,
  UPDATE_ADMIN_TICKETS
};
