const UPDATE_LOADED = 'support/UPDATE_LOADED';
const UPDATE_LOADING = 'support/UPDATE_LOADING';
const UPDATE_MY_TICKETS = 'support/UPDATE_MY_TICKETS';
const UPDATE_PAGINATION = 'support/UPDATE_PAGINATION';
const UPDATE_ADMIN = 'support/UPDATE_ADMIN';

export default {
  UPDATE_LOADED,
  UPDATE_LOADING,
  UPDATE_MY_TICKETS,
  UPDATE_PAGINATION,
  UPDATE_ADMIN
};
