const UPDATE_LOADED = 'support/UPDATE_LOADED';
const UPDATE_MY_TICKETS = 'support/UPDATE_MY_TICKETS';
const UPDATE_ADMIN = 'support/UPDATE_ADMIN';

export default {
  UPDATE_LOADED,
  UPDATE_MY_TICKETS,
  UPDATE_ADMIN
};
