const UPDATE_TWITCHACCOUNT = 'twitch/UPDATE_TWITCHACCOUNT';
const UPDATE_TWITCHAUTHURI = 'twitch/UPDATE_TWITCHAUTHURI';
const UPDATE_TWITCHDISCONNECT = 'twitch/UPDATE_TWITCHDISCONNECT';
const UPDATE_DISABLED = 'twitch/UPDATE_DISABLED';
const UPDATE_IS_LOADING = 'twitch/UPDATE_IS_LOADING';

export default {
  UPDATE_TWITCHACCOUNT,
  UPDATE_TWITCHAUTHURI,
  UPDATE_TWITCHDISCONNECT,
  UPDATE_DISABLED,
  UPDATE_IS_LOADING
};
