const UPDATE_UTILITIES = 'utilities/UPDATE_UTILITIES';
const UPDATE_TITLEGAME = 'utilities/UPDATE_TITLEGAME';
const UPDATE_DISABLED = 'utilities/UPDATE_DISABLED';

export default {
  UPDATE_UTILITIES,
  UPDATE_TITLEGAME,
  UPDATE_DISABLED
};
