const UPDATE_COMMANDS = 'commands/UPDATE_COMMANDS';
const UPDATE_ACCESSLEVELS = 'commands/UPDATE_ACCESSLEVELS';
const UPDATE_SINGLECOMMAND = 'commands/UPDATE_SINGLECOMMAND';
const UPDATE_ADDCOMMAND = 'commands/UPDATE_ADDCOMMAND';
const UPDATE_EDITCOMMAND = 'commands/UPDATE_EDITCOMMAND';
const UPDATE_DELCOMMAND = 'commands/UPDATE_DELCOMMAND';
const UPDATE_DISABLED = 'commands/UPDATE_DISABLED';
const UPDATE_IS_LOADING = 'commands/UPDATE_IS_LOADING';

export default {
  UPDATE_ACCESSLEVELS,
  UPDATE_COMMANDS,
  UPDATE_SINGLECOMMAND,
  UPDATE_ADDCOMMAND,
  UPDATE_EDITCOMMAND,
  UPDATE_DELCOMMAND,
  UPDATE_DISABLED,
  UPDATE_IS_LOADING
};
