const UPDATE_COMMANDS = 'commands/UPDATE_COMMANDS';
const UPDATE_PLUGINCOMMANDS = 'commands/UPDATE_PLUGINCOMMANDS';
const UPDATE_ACCESSLEVELS = 'commands/UPDATE_ACCESSLEVELS';
const UPDATE_SINGLECOMMAND = 'commands/UPDATE_SINGLECOMMAND';
const UPDATE_ADDCOMMAND = 'commands/UPDATE_ADDCOMMAND';
const UPDATE_EDITCOMMAND = 'commands/UPDATE_EDITCOMMAND';
const UPDATE_DELCOMMAND = 'commands/UPDATE_DELCOMMAND';
const UPDATE_DISABLED = 'commands/UPDATE_DISABLED';
const UPDATE_LOADING = 'commands/UPDATE_LOADING';
const UPDATE_LOADED = 'commands/UPDATE_LOADED';
const UPDATE_ACTIONSUCCESS = 'commands/UPDATE_ACTIONSUCCESS';

export default {
  UPDATE_ACCESSLEVELS,
  UPDATE_COMMANDS,
  UPDATE_PLUGINCOMMANDS,
  UPDATE_SINGLECOMMAND,
  UPDATE_ADDCOMMAND,
  UPDATE_EDITCOMMAND,
  UPDATE_DELCOMMAND,
  UPDATE_DISABLED,
  UPDATE_LOADING,
  UPDATE_LOADED,
  UPDATE_ACTIONSUCCESS
};
