const UPDATE_VARIABLES = 'variables/UPDATE_VARIABLES';
const UPDATE_ADDVARIABLE = 'variables/UPDATE_ADDVARIABLE';
const UPDATE_EDITVARIABLE = 'variables/UPDATE_EDITVARIABLE';
const UPDATE_REMOVEVARIABLE = 'variables/UPDATE_REMOVEVARIABLE';
const UPDATE_DISABLED = 'variables/UPDATE_DISABLED';

export default {
  UPDATE_VARIABLES,
  UPDATE_ADDVARIABLE,
  UPDATE_EDITVARIABLE,
  UPDATE_REMOVEVARIABLE,
  UPDATE_DISABLED
};
