const UPDATE_SEQUENCES = 'smartlife/UPDATE_SEQUENCES';
const UPDATE_DELSEQUENCE = 'smartlife/UPDATE_DELSEQUENCE';
const UPDATE_PAGINATION = 'smartlife/UPDATE_PAGINATION';
const UPDATE_SMARTLIFEACCOUNT = 'smartlife/UPDATE_SMARTLIFEACCOUNT';
const UPDATE_SMARTLIFEAUTHURI = 'smartlife/UPDATE_SMARTLIFEAUTHURI';
const UPDATE_SMARTLIFESCENES = 'smartlife/UPDATE_SMARTLIFESCENES';
const UPDATE_TRIGGERSMARTLIFESCENE = 'smartlife/UPDATE_TRIGGERSMARTLIFESCENE';
const UPDATE_CREATESEQUENCE = 'smartlife/UPDATE_CREATESEQUENCE';
const UPDATE_PLAYSEQUENCE = 'smartlife/UPDATE_PLAYSEQUENCE';
const UPDATE_SMARTLIFEMAXSTEPS = 'smartlife/UPDATE_SMARTLIFEMAXSTEPS';
const UPDATE_SMARTLIFEDISCONNECT = 'smartlife/UPDATE_SMARTLIFEDISCONNECT';
const UPDATE_DISABLED = 'smartlife/UPDATE_DISABLED';
const UPDATE_LOADING = 'smartlife/UPDATE_LOADING';
const UPDATE_LOADED = 'smartlife/UPDATE_LOADED';
const UPDATE_ACTIONSUCCESS = 'smartlife/UPDATE_ACTIONSUCCESS';

export default {
  UPDATE_SEQUENCES,
  UPDATE_DELSEQUENCE,
  UPDATE_PAGINATION,
  UPDATE_SMARTLIFEACCOUNT,
  UPDATE_SMARTLIFEAUTHURI,
  UPDATE_SMARTLIFESCENES,
  UPDATE_TRIGGERSMARTLIFESCENE,
  UPDATE_CREATESEQUENCE,
  UPDATE_PLAYSEQUENCE,
  UPDATE_SMARTLIFEMAXSTEPS,
  UPDATE_SMARTLIFEDISCONNECT,
  UPDATE_DISABLED,
  UPDATE_LOADING,
  UPDATE_LOADED,
  UPDATE_ACTIONSUCCESS
};
