const UPDATE_SMARTLIFEACCOUNT = 'smartlife/UPDATE_SMARTLIFEACCOUNT';
const UPDATE_SMARTLIFEAUTHURI = 'smartlife/UPDATE_SMARTLIFEAUTHURI';
const UPDATE_SMARTLIFEDISCONNECT = 'smartlife/UPDATE_SMARTLIFEDISCONNECT';
const UPDATE_DISABLED = 'smartlife/UPDATE_DISABLED';
const UPDATE_IS_LOADING = 'smartlife/UPDATE_IS_LOADING';

export default {
  UPDATE_SMARTLIFEACCOUNT,
  UPDATE_SMARTLIFEAUTHURI,
  UPDATE_SMARTLIFEDISCONNECT,
  UPDATE_DISABLED,
  UPDATE_IS_LOADING
};
